name: Publish .NET container to GitHub Packages

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  publish-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore Playground.slnx

      - name: Publish container image
        run: dotnet publish src/BlazorApp/BlazorApp.csproj --configuration Release /t:PublishContainer -p:ContainerRepository=${{ github.repository_owner }}/blazorapp
        env:
          DOTNET_CONTAINER_REGISTRY_UNAME: ${{ github.actor }}
          DOTNET_CONTAINER_REGISTRY_PWORD: ${{ secrets.GITHUB_TOKEN }}
